commands:
  - command: "discord"
    description: "Join our Discord server"
    usage: "/discord"
    aliases: ["dc"]
    permission: "lsc.discord"
    text: "Join our Discord server at discord.gg/example"
    type: "SIMPLE"
    linkInventory: true
    name: "&9Discord"
    material: "PLAYER_HEAD"
    headValue: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjcyMjA5OGFlNzljN2FiZjAwMmZlOTY4NGM3NzNlYTcxZGI4OTE5YmIyZWYyMDUzZWEwYzA2ODRjNWExY2U0ZiJ9fX0="
    slot: 11
  - command: "links"
    description: "View all our links"
    usage: "/links"
    aliases: ["l"]
    permission: "lsc.links"
    type: "LINK_INVENTORY"

linkInventory:
  title: "&bʟɪɴᴋs"
  fillerMaterial: "BLACK_STAINED_GLASS_PANE"